require("nvim-tree").setup { -- BEGIN_DEFAULT_OPTS
      auto_reload_on_write = true,
      create_in_closed_folder = false,
      disable_netrw = false,
      hijack_cursor = true,
      hijack_netrw = true,
      hijack_unnamed_buffer_when_opening = false,
     -- ignore_buffer_on_setup = false,
     -- open_on_setup = false,
      --open_on_setup_file = false,
      open_on_tab = false,
      -- focus_empty_on_setup = false,
      ignore_buf_on_tab_change = {},
      sort_by = "name",
      root_dirs = {},
      prefer_startup_root = false,
      sync_root_with_cwd = false,
      reload_on_bufenter = false,
      respect_buf_cwd = false,
      on_attach = "disable",
      remove_keymaps = false,
      select_prompts = false,
      view = {
        adaptive_size = false,
        centralize_selection = false,
        width = 30,
        hide_root_folder = false,
        side = "left",
        preserve_window_proportions = false,
        number = false,
        relativenumber = false,
        signcolumn = "yes",
        mappings = {
          custom_only = false,
          list = {
					  { key = { "<Leader>n<CR>", "<Leader>no", "<2-LeftMouse>" }, action = "edit" },
    				{ key = "<Leader>n<C-e>",                          action = "edit_in_place" },
    				{ key = "<Leader>nO",                              action = "edit_no_picker" },
    				{ key = "<Leader>n]", 										       	 action = "cd" },
    				{ key = "<Leader>nv",                              action = "vsplit" },
 	  				{ key = "<Leader>nh",                					     action = "split" },
    				{ key = "<Leader>nt",                        		   action = "tabnew" },
				    { key = "<Leader>n<",                              action = "prev_sibling" },
				    { key = "<Leader>n>",                              action = "next_sibling" },
				    { key = "<Leader>nP",                              action = "parent_node" },
				    { key = "<Leader>n<BS>",                           action = "close_node" },
				    { key = "<Leader>n<Tab>",                          action = "preview" },
				    { key = "<Leader>nK",                              action = "first_sibling" },
				    { key = "<Leader>nJ",                              action = "last_sibling" },
				    { key = "<Leader>nI",                              action = "toggle_git_ignored" },
				    { key = "<Leader>nH",                              action = "toggle_dotfiles" },
				    { key = "<Leader>nU",                              action = "toggle_custom" },
				    { key = "<Leader>nR",                              action = "refresh" },
				    { key = "<Leader>na",                              action = "create" },
				    { key = "<Leader>nd",                              action = "remove" },
				    { key = "<Leader>nD",                              action = "trash" },
				    { key = "<Leader>nr",                              action = "rename" },
				    { key = "<Leader>n<C-r>",                          action = "full_rename" },
				    { key = "<Leader>nx",                              action = "cut" },
				    { key = "<Leader>nc",                              action = "copy" },
				    { key = "<Leader>np",                              action = "paste" },
				    { key = "<Leader>ny",                              action = "copy_name" },
				    { key = "<Leader>nY",                              action = "copy_path" },
				    { key = "<Leader>ngy",                             action = "copy_absolute_path" },
				    { key = "<Leader>n[e",                             action = "prev_diag_item" },
				    { key = "<Leader>n[c",                             action = "prev_git_item" },
				    { key = "<Leader>n]e",                             action = "next_diag_item" },
				    { key = "<Leader>n]c",                             action = "next_git_item" },
				    { key = "<Leader>n-",                              action = "dir_up" },
				    { key = "<Leader>ns",                              action = "system_open" },
				    { key = "<Leader>nf",                              action = "live_filter" },
				    { key = "<Leader>nF",                              action = "clear_live_filter" },
				    { key = "<Leader>nq",                              action = "close" },
				    { key = "<Leader>nW",                              action = "collapse_all" },
				    { key = "<Leader>nE",                              action = "expand_all" },
				    { key = "<Leader>nS",                              action = "search_node" },
				    { key = "<Leader>n.",                              action = "run_file_command" },
				    { key = "<Leader>n<C-k>",                          action = "toggle_file_info" },
				    { key = "<Leader>ng?",                             action = "toggle_help" },
				    { key = "<Leader>nm",                              action = "toggle_mark" },
				    { key = "<Leader>nbmv",                            action = "bulk_move" },
					},
        },
        float = {
          enable = false,
          open_win_config = {
            relative = "editor",
            border = "rounded",
            width = 30,
            height = 30,
            row = 1,
            col = 1,
          },
        },
      },
      renderer = {
        add_trailing = false,
        group_empty = false,
        highlight_git = false,
        full_name = false,
        highlight_opened_files = "none",
        root_folder_modifier = ":~",
        indent_width = 2,
        indent_markers = {
          enable = false,
          inline_arrows = true,
          icons = {
            corner = "└",
            edge = "│",
            item = "│",
            bottom = "─",
            none = " ",
          },
        },
        icons = {
          webdev_colors = true,
          git_placement = "before",
          padding = " ",
          symlink_arrow = " ➛ ",
          show = {
            file = true,
            folder = true,
            folder_arrow = true,
            git = true,
          },
          glyphs = {
            default = "",
            symlink = "",
            bookmark = "",
            folder = {
              arrow_closed = "",
              arrow_open = "",
              default = "",
              open = "",
              empty = "",
              empty_open = "",
              symlink = "",
              symlink_open = "",
            },
            git = {
              unstaged = "✗",
              staged = "✓",
              unmerged = "",
              renamed = "➜",
              untracked = "★",
              deleted = "",
              ignored = "◌",
            },
          },
        },
        special_files = { "Cargo.toml", "Makefile", "README.md", "readme.md" },
        symlink_destination = true,
      },
      hijack_directories = {
        enable = true,
        auto_open = true,
      },
      update_focused_file = {
        enable = false,
        update_root = false,
        ignore_list = {},
      },
      --ignore_ft_on_setup = {},
      --system_open = {
      --  cmd = "",
      --  args = {},
      --},
      diagnostics = {
        enable = false,
        show_on_dirs = false,
        debounce_delay = 50,
        icons = {
          hint = "",
          info = "",
          warning = "",
          error = "",
        },
      },
      filters = {
        dotfiles = false,
        custom = {},
        exclude = {},
      },
      filesystem_watchers = {
        enable = true,
        debounce_delay = 50,
      },
      git = {
        enable = true,
        ignore = true,
        show_on_dirs = true,
        timeout = 400,
      },
      actions = {
        use_system_clipboard = true,
        change_dir = {
          enable = true,
          global = false,
          restrict_above_cwd = false,
        },
        expand_all = {
          max_folder_discovery = 300,
          exclude = {},
        },
        file_popup = {
          open_win_config = {
            col = 1,
            row = 1,
            relative = "cursor",
            border = "shadow",
            style = "minimal",
          },
        },
        open_file = {
          quit_on_open = true,
          resize_window = true,
          window_picker = {
            enable = true,
            chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
            exclude = {
              filetype = { "notify", "packer", "qf", "diff", "fugitive", "fugitiveblame" },
              buftype = { "nofile", "terminal", "help" },
            },
          },
        },
        remove_file = {
          close_window = true,
        },
      },
      trash = {
        cmd = "gio trash",
        require_confirm = true,
      },
      live_filter = {
        prefix = "[FILTER]: ",
        always_show_folders = true,
      },
      log = {
        enable = false,
        truncate = false,
        types = {
          all = false,
          config = false,
          copy_paste = false,
          dev = false,
          diagnostics = false,
          git = false,
          profile = false,
          watcher = false,
        },
      },
    } -- END_DEFAULT_OPTS



local which_key = require("which-key")

local NvimTreeKeys = { -- BEGIN_DEFAULT_MAPPINGS
	["<Leader>"] = {
		n = {
		name = "NvimTree",
			["<CR>"] = {"edit" },
	  	o = {"edit" },
			["<C-e>"] = {"edit_in_place" },
    	O = {"edit_no_picker" },
   		["]"] = {"cd in the directory"},
   		v = {"vertical split" },
  		h = {"horizontal split" },
  		t = {"new tab" },
    	P = {"parent node" },
			["<BS"] = {"close node" },
	 		["<Tab>"] = {"preview" },
	    K = {"first sibling" },
	    J = {"last sibling" },
	    I = {"toggle git ignored" },
	    H = {"toggle dotfiles" },
	    U = {"toggle custom" },
	    R = {"refresh" },
	    a = {"create" },
	    d = {"remove" },
	    D = {"trash" },
	    r = {"rename" },
	    ["<C-r>"] = {"full rename" },
	    x = {"cut" },
	    c = {"copy" },
	    p = {"paste" },
	    y = {"copy name" },
	    Y = {"copy path" },
	    gy = {"copy absolute path" },
			["[e"] = {"prev diag item" },
			["[c"] = {"prev git item" },
			["]e"] = {"next diag item" },
			["]c"] = {"next git item" },
			["-"] = {"dir up" },
	    s = {"system open" },
	    f = {"live filter" },
	    F = {"clear live filter" },
	    q = {"close" },
	    W = {"collapse all" },
	    E = {"expand all" },
	    S = {"search node" },
	    ["."] = { "<Leader>n.",   "run file command" },
	    ["<C-k>"] = {"toggle file info" },
			["g?"] = {"toggle help" },
	    m = {"toggle mark" },
	    ["bmv"] = {"bulk move" },
  } -- END_DEFAULT_MAPPINGS
}
}

--local WhichKeyOpts = { buffer = "NvimTree_1"}
which_key.register(NvimTreeKeys)
